- name: Install packages
  apt:
    name:
      - apache2
      - python3-mysqldb
      - mariadb-server
      - libapache2-mod-php7.4
      - php7.4-mysql
    state: present
    update_cache: yes
    
- name: Enable php
  apache2_module:
    name: php7.4
    state: present

- name: Enable http2
  apache2_module:
    name: http2
    state: present

- name: Fix /var/www owner
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes

- name: Remove anon users
  mysql_user:
   name: ''
   host_all: yes
   state: absent

- name: Root only from localhost socket
  mysql_user:
   name: root
   plugin: unix_socket
   state: present

- name: Drop test db
  mysql_db: 
    name: test
    state: absent

- name: Create rw mysql user
  mysql_user:
    name: "{{ mysql_user }}"
    host: '%'
    password: "{{ mysql_passwd }}"
    priv: '*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP'
    update_password: always
    state: present