---
- name: Install deps
  apt:
    name:
      - rabbitmq-server
    state: present
    update_cache: yes

- name: Enable and run service
  systemd:
    daemon_reload: yes
    name: rabbitmq-server
    enabled: yes
    state: started

- name: Enable MQTT and Web management plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_mqtt
    state: enabled

- name: Add rabbitmq user
  rabbitmq_user:
    user: pi
    password: raspberry
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    tags: management,administrator
    state: present
