- name: Install deps
  apt:
    name:
      - nodejs
      - python3-cryptography
    state: present
    update_cache: yes
- name: Install a yarn
  apt:
    deb: https://github.com/yarnpkg/yarn/releases/download/v1.22.17/yarn_1.22.17_all.deb

# TODO Find out why creating the user with `home=/srv/zenko/s3` does not respect `create_home: no` when there's no `/srv/zenko`.
- name: Create zenko cloudserver service user
  user:
    name: zenko-s3
    shell: /usr/sbin/nologin
    create_home: yes
    home: /var/zenko-s3
    system: yes
    state: present

- name: Create /srv/zenko-s3 dir
  file:
    path: /srv/zenko-s3
    state: directory
    owner: zenko-s3
    group: zenko-s3
    mode: '0755'

- name: Checkout zenko cloudserver
  become: yes
  become_user: zenko-s3
  git:
    repo: 'https://github.com/scality/cloudserver.git'
    dest: /srv/zenko-s3
    version: "8.3.1"
    update: no

- name: Install zenko cloudserver packages
  become: yes
  become_user: zenko-s3
  community.general.yarn:
    path: /srv/zenko-s3
    production: yes

# NOTE An ssl connection is required for cyberduck to connect
- name: Create /srv/zenko-s3/ssl-cert dir
  file:
    path: "{{ item }}"
    state: directory
    owner: zenko-s3
    group: zenko-s3
    mode: '0700'
  loop:
      - /srv/zenko-s3/ssl-cert
      - /srv/zenko-s3/ssl-cert/private

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  become: yes
  become_user: zenko-s3
  openssl_privatekey:
    path: /srv/zenko-s3/ssl-cert/private/raspberrypi.local.pem

- name: Generate an OpenSSL Certificate Signing Request
  become: yes
  become_user: zenko-s3
  openssl_csr:
    path: /srv/zenko-s3/ssl-cert/raspberrypi.local.csr
    privatekey_path: /srv/zenko-s3/ssl-cert/private/raspberrypi.local.pem
    common_name: raspberrypi.local

- name: Generate a Self Signed OpenSSL certificate
  become: yes
  become_user: zenko-s3
  openssl_certificate:
    path: /srv/zenko-s3/ssl-cert/raspberrypi.local.crt
    privatekey_path: /srv/zenko-s3/ssl-cert/private/raspberrypi.local.pem
    csr_path: /srv/zenko-s3/ssl-cert/raspberrypi.local.csr
    provider: selfsigned

- name: Add certificate to config
  become: yes
  become_user: zenko-s3
  json_patch:
    src: /srv/zenko-s3/config.json
    operations:
      - op: add
        path: "/certFilePaths"
        value:
          key: "/srv/zenko-s3/ssl-cert/private/raspberrypi.local.pem"
          cert: "/srv/zenko-s3/ssl-cert/raspberrypi.local.crt"
          #ca: ""

# Add endpoint so it can be reached from raspberrypi.local
- name: Set restEnpoint for raspberrypi.local
  become: yes
  become_user: zenko-s3
  json_patch:
    src: /srv/zenko-s3/config.json
    operations:
      - op: add
        path: "/restEndpoints/raspberrypi.local"
        value: "eu-central-1"

- name: Set auth thing
  become: yes
  become_user: zenko-s3
  json_patch:
    src: /srv/zenko-s3/conf/authdata.json
    operations:
      - op: replace
        path: "/accounts"
        value:
          - name: "{{ zenko_user.name }}"
            email: "{{ zenko_user.email }}"
            arn: "arn:aws:iam::123456789016:root"
            canonicalID: "http://acs.zenko.io/accounts/service/pi"
            shortid: "123456789016"
            keys:
              - access: "{{ zenko_user.access_key }}"
                secret: "{{ zenko_user.secret_key }}"

- name: Install systemd service
  copy:
    src: files/zenko-s3.service
    dest: /etc/systemd/system/
    owner: root
    mode: '0644'

- name: Enable and run service
  systemd:
    daemon_reload: yes
    name: zenko-s3
    enabled: yes
    state: started
