# Based on https://pimylifeup.com/raspberry-pi-dns-server/
- name: Deploy a basic DNS service
  hosts: rpi
  gather_facts: no
  become: yes
  tasks:
    - name: Install DNSmasq
      apt:
        name: dnsmasq
        state: present
        update_cache: yes
    - name: Do not forward plain names to upstream
      replace:
        path: /etc/dnsmasq.conf
        regexp: '^#domain-needed'
        replace: 'domain-needed'
    - name: Do not forward local reverse-lookup queries to upstream
      replace:
        path: /etc/dnsmasq.conf
        regexp: '^#bogus-priv'
        replace: 'bogus-priv'
    - name: Skip readding "/etc/resolv.conf"
      replace:
        path: /etc/dnsmasq.conf
        regexp: '^#no-resolv'
        replace: 'no-resolv'
    - name: Set upstream servers # Latency ordered from my location
      lineinfile:
        dest: /etc/dnsmasq.conf
        regexp: '^#server='
        insertafter: "^#server"
        line: "server={{ item }}"
      loop:
        # Resolver1.pitchile.cl
        - '170.247.94.17'
        # Resolver2.pitchile.cl
        - '170.247.94.18'
        # Verysign
        - '192.58.128.30'
        # Cloudflare
        - '1.1.1.1'
    - name: Set cache size
      replace:
        path: /etc/dnsmasq.conf
        regexp: '^#cache-size='
        replace: 'cache-size=1000'
    - name: Reload service
      service:
        name: dnsmasq
        state: reloaded
        enabled: yes

