- name: Deploy a simple lamp stack
  hosts: rpi
  vars_files:
    - http.vault.yml
  gather_facts: no
  become: yes
  vars:
    mysql_user: "{{ vault_mysql_user }}"
    mysql_passwd: "{{ vault_mysql_passwd }}"
  tasks:
    - name: Install packages
      apt:
        name:
          - apache2
          - python-mysqldb
          - mariadb-server
          - libapache2-mod-php7.3
          - php7.3-mysql
        state: present
        update_cache: yes
    - name: Enable php
      apache2_module:
        name: php7.3
        state: present
    - name: Enable http2
      apache2_module:
        name: http2
        state: present
    - name: Fix /var/www owner
      file:
        path: /var/www
        owner: www-data
        group: www-data
        recurse: yes
    - name: Secure mysql # WARNING: This will not work on MariaDB>=10.4 (mysql.user becomes RO)
      #TODO Make it idempotent
      command: /usr/bin/mysql -u root -e {{ item | quote }}
      with_items:
        # Remove anon users
        - "DELETE FROM mysql.user WHERE User='';"
        # Allow root only from localhost root processes
        - "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
        - "UPDATE mysql.user SET Plugin='unix_socket' WHERE User='root';"
        - "UPDATE mysql.user SET Password='' WHERE User='root';"
        # Drop test db
        - "DROP DATABASE IF EXISTS test; DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%';"
        # Flush Permissions
        - "FLUSH PRIVILEGES;"
    - name: Create rw mysql user
      mysql_user:
        name: "{{ mysql_user }}"
        host: '%'
        password: "{{ mysql_passwd }}"
        priv: '*.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP'
        update_password: always
        state: present